### ISSUE TITLE
Button text for multiple FU fields always changes to the text of the first field

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms-uploads#310] opened 2017-11-13 15:06 UTC
If I have two or more file upload fields, the button text for the subsequent fields always takes the value of the text that was set for the first field.

**Comment by polevaultweb** [comment] 2017-11-18 22:38
Duplicate of https://github.com/wpninjas/ninja-forms-uploads/issues/311

**Closed by polevaultweb** 2017-11-18 22:38 UTC
Labels: bug
